### ISSUE TITLE
Checking for null in SQL

### ISSUE THREAD

**Issue by malx122** [Starcounter/Starcounter#2362]
Hm, I thought I had done this before in many places but it doesnt seem to work now:
```
            int counter = 0;
            foreach(Template tr in Db.SQL<Template>("SELECT t FROM Template t WHERE t.Parent=?",null))
            {
                    counter++;
            }
```
Gives me a counter = 0, no errors

```
            int counter = 0;
            foreach(Template tr in Db.SQL<Template>("SELECT t FROM Template t"))
            {
                if (tr.Parent == null)
                    counter++;
            }
```
Gives me a counter = 10, which is the result I was expecting from both examples.

What is wrong?

**Comment by dan31** [comment]
Bug fixed, test exists, closing it.

**Comment by k-rus** [comment]
Are you sure that the bug was fixed? I think the bug was never fixed.

**Comment by dan31** [comment]
@k-rus, I'm following your last comments. What bug and fix they relate to?

**Comment by dan31** [comment]
Here is the reference:
> Fixes #2362.
> Added test with selection on existing reference. Part of #2362.

**Comment by dan31** [comment]
Okay, this is not fixed, but reproduced. This probably goes to code gen filter path, see comment: https://github.com/Starcounter/Starcounter/issues/2362#issuecomment-61771576. @alemoi, bump.

**Comment by chrhol** [comment]
BUMP. Found this issue when going through some of the tests in the pnext blacklist.

Looks like this is still an issue. Can be reproduced in both develop and pnext by running the `SelectOnNull2362_test` (in `Level1\src\Samples\TestApps\SelectOnNull2362\`) . In develop the test is set to not run as default on the buildserver and in pnext it's currently blacklisted.

**Comment by alemoi** [comment]
I checked the code generation and its seems alright on the first look. Data stream has value: 5 0 0 0 0 0 (meaning null value). Instruction array is: string property (13) ORed with shifted data index (2): 525, string variable: 5,  string equality comparison: 21.
Iterator is created with range (full range): 5 0 0 0 0 0 and 13 0 0 0 1 255 255 255 255 255 255 255 255.

During first iteration (MoveNext) kernel is not returning anything, so either some input is wrong (like null value for string is encoded differently) or there is bug in the code.

@eriohl are there any specifics in generated code for null values that we don't know of? Some input would be appreciated.

**Comment by eriohl** [comment]
Are we still discussing reference values? Consider that there is no reference tracking so that if the target reference is deleted the column value of the referenced record is not updated. So the query processor needs evaluate the reference to determine is it is invalid. Maybe the query processor doesn't do this correctly? (This is why IS NULL can't be evaluated against an index in the case of references.)

**Comment by alemoi** [comment]
If I set value("aaa") to LastName of the person, and query becomes `Person q = Db.SQL<Person>("select p from Person p where LastName = ?", "aaa").First;` then result is correctly retrieved (same instruction stream 525 5 21, different value stream of course because of "aaa"). So it must be something with `null` value and code generation scan I suppose.

**Comment by alemoi** [comment]
> Are we still discussing reference values? Consider that there is no reference tracking so that if the target reference is deleted the column value of the referenced record is not updated. So the query processor needs evaluate the reference to determine is it is invalid. Maybe the query processor doesn't do this correctly? (This is why IS NULL can't be evaluated against an index in the case of references.)

Does this mean that generated filter can not handle NULL reference values properly?

**Comment by k-rus** [comment]
> Are we still discussing reference values? Consider that there is no reference tracking so that if the target reference is deleted the column value of the referenced record is not updated. So the query processor needs evaluate the reference to determine is it is invalid. Maybe the query processor doesn't do this correctly? (This is why IS NULL can't be evaluated against an index in the case of references.)

Do you mean that the kernel does not provide support for comparing null references, e.g., through filter? Then the query processor should not generate filter and instead retrieve values from the kernel and compare them in the managed code accordantly, right?

**Comment by eriohl** [comment]
> Do you mean that the kernel does not provide support for comparing null references, e.g., through filter?

Not sure what you are asking but what I meant was that you can't rely on sorting in indexes because column value and indexes are not updated when the target of a weak reference is deleted (you can only be sure that a weak reference is valid when you check the target). Thus you can't use indexes to answer IS NULL or IS NOT NULL on a reference field (because you need to check every reference). But surely this is known already. The optimizer handles this properly I think (at least it did). So I'm kind of confused by your question.

> Then the query processor should not generate filter and instead retrieve values from the kernel and compare them in the managed code accordantly, right?

```*_get_reference``` evaluates the weak reference. This is not done in managed code.

**Comment by alemoi** [comment]
@eriohl actually I understood your response the same way as @k-rus did: that filter codegen should not be generated for conditions involving reference values NULL comparisons :) However now I'm quite confused over what should be done to fix the issue. I would appreciate some clarification. Thank you.

**Comment by eriohl** [comment]
I don't even know if this is the problem, or even a problem. I just suggested that it migth be. Is it confirmed to be a problem then? Looking at the reproduce the target is not even set so in this case is seems not to be it. And if it only happens in release build then it is obviously not this that is the problem.

**Comment by eriohl** [comment]
Since NULL = NULL is NULL in SQL it seems to me that the original example is actually correct. We have some special SQL adaption that exchanges = NULL for IS NULL then?

**Comment by eriohl** [comment]
Ahh. When you are referring to comparisons in the kernel you are then referring to the native filter and not the kernel at all? Then it makes more sense.

**Comment by alemoi** [comment]
Yes, its the comparison in generated condition filter, with the input code and data stream given above.

**Comment by eriohl** [comment]
@alemoi In the string example you have: Load string variable, load string column, equal compare. Right? If then either or both of the variable or the column value is undefined then the result of that comparison is undefined. That is: No hit. Right?

**Comment by alemoi** [comment]
> @alemoi In the string example you have: Load string variable, load string column, equal compare. Right? If then either or both of the variable or the column value is undefined then the result of that comparison is undefined. That is: No hit. Right?

If considering NULL an undefined value for string, then seems yes :) @k-rus what is your verdict on this matter?

**Comment by eriohl** [comment]
Ok. That seems perfectly accurate to me. I am not working with query processing any longer so you need to check the code but as far as I remember an equal compare between NULL and NULL evaluates to NULL as in SQL.

**Comment by k-rus** [comment]
> Ok. That seems perfectly accurate to me. I am not working with query processing any longer so you need to check the code but as far as I remember an equal compare between NULL and NULL evaluates to NULL as in SQL.

You are correct. If one of the values is NULL then the result is unknown, i.e., NULL. I am always forget about this.
Here is a [link](http://stackoverflow.com/a/9581790/840340) to discussion that it is common SQL behaviour.

**Comment by k-rus** [comment]
I consider this issue as closed, since no bug is here. I fixed the test to succeed according current semantics and enabled it.

**Comment by andwah** [comment]
> If I set value("aaa") to LastName of the person, and query becomes Person q = Db.SQL<Person>("select p from Person p where LastName = ?", "aaa").First; then result is correctly retrieved


I did this test and i as @malx122 expected that both should return the same result. But they did not.
```
Person p = new Person();

Person p1 = Db.SQL<Person>("select p from Person p where p.LastName = ?", null).First;
// p1 is null

Person p2 = Db.SQL<Person>("select p from Person p where p.LastName IS NULL").First;
// p2 is NOT null
```

**Comment by k-rus** [comment]
> I did this test and i as @malx122 expected that both should return the same result. But they did not.
> 
> Person p = new Person();
> 
> Person p1 = Db.SQL<Person>("select p from Person p where p.LastName = ?", null).First;
> // p1 is null
> 
> Person p2 = Db.SQL<Person>("select p from Person p where p.LastName IS NULL").First;
> // p2 is NOT null

See the discussion above. It is correct behaviour according to standard semantics of NULL.

**Comment by andwah** [comment]
@k-rus Yes i know but i **expected** the result to be different, so maybe many other users will too? 
So with this little example we can see what the result will be.

**Comment by k-rus** [comment]
> Yes i know but i expected the result to be different, so maybe many other users will too? 
> So with this little example we can see what the result will be.

We will not change the semantics of NULL just like this, since it might bring other issues, which you don't think of. We have issue #2217, which is suspended now, where we discuss operators in the presence of NULL. We understand that standard semantics of NULL has shortcomings, but we don't want to replace one shortcomings with another shortcomings.

If you have good proposal with solid fundamentals under it, I would be happy to hear.

**Comment by k-rus** [comment]
The problem is that semantics of NULL is developer specific. It might be just not-set value, but might mean unknown value. The two options mean different behaviour. In the second case it is not possible to say if one unknown value is the same or not as another unknown, thus the result is NULL, i.e., unknown. If the first semantic is meant then `IS NULL` has to be used to give the hint to our engine.
