### ISSUE TITLE
Installer window does not open in front

### ISSUE THREAD

**Issue by warpech** [Starcounter/Starcounter#2453]
Installer window does not open in front, but rather in back (behind all the other windows).

This causes confusion because when I have many windows opened, it seems that the installer does not start at all.

The screenshot below shows what happens after I doubleclick the intaller exe:

![installer-window-on-back](https://cloud.githubusercontent.com/assets/566463/5470127/5eb9a0ce-85e4-11e4-8d14-7b891887169e.png)

System: Windows 8.1

**Comment by warpech** [comment]
Still happens to me and it is very annoying. When my Windows Explorer is full-screen, then the installer window is not visible at all, until I minimise the Explorer first.

Does it happen to anyone else?

**Comment by miyconst** [comment]
Sometimes this also happens to me, but only when I install next version of SC over the old one.
After uninstallation finished, the new installation window appears underneath other windows.

**Comment by tomalec** [comment]
Same here.

**Comment by k-rus** [comment]
This annoying issue was already reported in #1972. I found also another old issue #884, which was fixed, but not any more.

**Comment by warpech** [comment]
I just added a CodeNight label about it

@andwah any chance of fixing this before CodeNight?

**Comment by andwah** [comment]
Pushed a fix for this. i hope it works for all.

**Comment by warpech** [comment]
Still reproducible in 2.1.397 nightly (uninstalling 2.1.397 or 2.1.177 gives the same effect).

This time with the prompt to uninstall the previous version:

![bug](https://cloud.githubusercontent.com/assets/566463/11070083/f2b2ed9c-87d9-11e5-82f0-cd9726ef3b8b.gif)

**Comment by warpech** [comment]
When done, pls also close #1972

**Comment by warpech** [comment]
This is still a problem. Very confusing for anyone who upgrades Starcoutner using the installer.

**Comment by bigwad** [comment]
Up. Still actual

**Comment by andwah** [comment]
I need to take another deeper look at this problem.. seems not to work on some Windows versions.

**Comment by andwah** [comment]
Messageboxes is now "TopMost"

Fixed 5a70da8ca6129dacd1f30bbcee8e5682b4cb626a

**Comment by warpech** [comment]
This seems to be fixed for me now. Good job @andwah!
