### ISSUE TITLE
Unable to upload large files

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3133]
I am trying to upload file of 6mb size.

For this I have changed Starcounter gateway settings:

```xml
<MaximumReceiveContentLength>10485760</MaximumReceiveContentLength>
```

In 
```
C:\Users\IEUser\Documents\Starcounter\Personal\scnetworkgateway.xml
```

Restarted server to get setting loaded. But still, trying to upload the file ends up with the error:

```
net::ERR_CONNECTION_ABORTED
```

Should I do something else?

cc @alemoi

**Comment by alemoi** [comment]
My bad, because I found a missing warning entry report in the server log. Now I fixed that there is a warning logged to server log: 
`20151203T114436 Warning sc://alemoi/personal/networkgateway Starcounter - Gateway XML: MaximumReceiveContentLength parameter exceeds maximum value of 2096936. Value of 2096936 will be used.`

The maximum value for this parameter is now 2096936. If people would like to use a bigger upload we suggest using a custom uploader based on WebSockets. I set the default value for the new installation to be 1048576.

Thank you for reporting!

**Comment by alemoi** [comment]
The fix I can provide in daily build for you! So you don't need to wait for nightly.

**Comment by miyconst** [comment]
Thank you @alemoi, I don't need it today, but nice having it fixed. I will close the issue after testing it.

**Comment by alemoi** [comment]
The reason for this limitation is simple: where there 2 Megabytes, there are 10 and 100. That's why I set the limit to 2 Mb approximately and everything on top of that should be handled using user-code streaming, where I am suggesting WebSockets.

**Comment by miyconst** [comment]
Starcounter `2.1.733` still not able to upload a file of size `4.3mb`.

```xml
<MaximumReceiveContentLength>41943040</MaximumReceiveContentLength>
```

**Comment by alemoi** [comment]
Yes, the old gateway configs contains a value of 4Mb which is not supported now. I was thinking now and I will override the value of old configs in the installer. I want to publish an example of streaming data upload using websockets. Will talk to @andwah, he has one I think.

**Comment by miyconst** [comment]
@alemoi, I have manually changed the config file by adding a `0` in the end, so it should be `40mb`.

**Comment by miyconst** [comment]
Looks like I misunderstood @alemoi. Current limitation of Starcounter is maximum 2mb of request length.

The bigger files should be send over WebSocket.

@warpech could you post here a link once you get any response from Tunity about the custom component to send files over WebSocket?

**Comment by warpech** [comment]
> @warpech could you post here a link once you get any response from Tunity about the custom component to send files over WebSocket?

It is Heads (@careri). I asked, waiting for response.

**Comment by miyconst** [comment]
Large files should be uploaded with WebSocket. Example is available in KitchenSink: https://github.com/StarcounterSamples/KitchenSink/blob/master/src/KitchenSink/FileUploadPage.json.cs.

Maximum request length is 4bm, everything over should be uploaded with WebSocket.

Closing this issue.
