### ISSUE TITLE
DbException occurred in Starcounter.dll

### ISSUE THREAD

**Issue by jwillmer** [Starcounter/Starcounter#3134]
This problem is reoccurring every now and then:
I have two Projects in my Solution. One is created via Starcounter project template and the other is a library there I put my database models.
Sometimes if I change something and run the solution I get an DbException. I think it is a caching problem. Cleaning & rebuilding of the solution does not help every time, sometimes the only option is to delete the database.

![error](https://cloud.githubusercontent.com/assets/1503577/11556442/3d6130b0-99af-11e5-8eb4-af4253fc09cd.png)

```
   bei Starcounter.Query.QueryPreparation.PrepareOrExecuteQuery[T](String query, Boolean slowSql, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Query\QueryPreparation.cs:Zeile 67.
   bei Starcounter.Query.Sql.SqlEnumCache.CacheOrExecuteEnumerator[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Query\SQL\_SqlEnumCache.cs:Zeile 127.
   bei Starcounter.Db.FullQueryProcess[T](String query, Boolean slowSQL, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Mock\Db.cs:Zeile 126.
   bei Starcounter.Db.SlowSQL(String query, Object[] values) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Mock\Db.cs:Zeile 104.
   bei PIM.DemoData.<>c.<ClearDatabase>b__1_0() in D:\Projects\ProjectName\ProjectName\PIM\DemoData.cs:Zeile 31.
   bei Starcounter.Db.Transact(Action action, UInt32 flags, Boolean forceSnapshot, Int32 maxRetries) in c:\TeamCity\TeamCity8\buildAgent\work\sc-develop-daily-218\Level1\src\Starcounter\Db.cs:Zeile 192.
```

**Comment by per-samuelsson** [comment]
@jwillmer 

Thanks for reporting this. I'm afraid I dont have an instant answer to what could be the cause. 

The `ScErrSchemaCodeMismatch` error you get indicates the code and the database data is not in sync. I have in the back of my head we've had issues regardin this before. Lets see if there are some clues out there.

**Comment by miyconst** [comment]
I have similar issue when I was trying to run some SQL query over a database class before accessing that class.

Starting an app is not loading it's classes into database, you have to do any kind of manipulation with that class, and if you try to access it with SQL, then it throws such exception.

**Comment by per-samuelsson** [comment]
Looks like there is an open issue #2439 (looooong one) that at least have similar traits on the surface. Cant tell for sure its the same thing though.

That issue in turn reference issue #2460, which might be a clue too.

Lets see if someone else can give any leads to this case? Not sure who to ping though. @k-rus? @chrhol?

**Comment by per-samuelsson** [comment]
> Starting an app is not loading it's classes into database, you have to do any kind of manipulation with that class, and if you try to access it with SQL, then it throws such exception.

Ah, this old case I remember. Thanks @miyconst. Does it still apply, do you know?

We are using a lazy-loading thing, to simulate what the CLR does. So when you start your application, we don't instantly load classes. And in the past, we had problems that doing SQL before classes where loaded didn't trigger the load (like they should). But I was thinking that was fixed. Maybe it was only fixed in SELECT (and you are doing DELETE), or not fixed at all.

**Comment by k-rus** [comment]
> Maybe it was only fixed in SELECT (and you are doing DELETE), or not fixed at all.

This should be not difficult to fix, since DELETE is complete implemented C#. See `_SqlProcessor.cs`. @per-samuelsson can you look?

**Comment by miyconst** [comment]
No, the issue is not solved.

It loads only one class which is requested by `SELECT`.

```cs
[Database]
public class Project : Set {
	
	...

	public CreatedBy CreatedBy {
		get {
			return Db.SQL<CreatedBy>(@"SELECT p FROM CreatedBy p WHERE p.WhatIs = ?", this).First;
		}
	}
}
```

```sql
SELECT * FROM Sweoffshore.Project
```

```
Failed to process query: SELECT p FROM CreatedBy p WHERE p.WhatIs = ?: Unknown class CreatedBy. Unknown property WhatIs of class CreatedBy. View the log for more details.
```

**Comment by dan31** [comment]
@k-rus still an issue?

**Comment by k-rus** [comment]
> @k-rus still an issue?

I don't know. Nobody wrote that it was fixed, which usually it means it is not fixed.
