### ISSUE TITLE
Extend diagnostics from weaver

### ISSUE THREAD

**Issue by per-samuelsson** [Starcounter/Starcounter#3420]
From https://github.com/Starcounter/Starcounter/issues/3413#issuecomment-191230635:

> What I'm currently thinking about is to support some kind of simple guide and a convenience CLI for the weaver to write out diagnostic information. So that when this kind of error occur, we point the user to a guide that basically ask them to

> 1. Open a prompt
> 2. Run ```app-diag path\to\app.exe```

> and `app-diag` is basically just wrapping a call to `scweaver --nocache --verbosity=diagnostic path\to\app.exe` and **we extend what we output there a little further, to include stuff such as what files are actually considered, which files have been ignored by `weaver.ignore`, all paths we use to resolve dependencies, etc**.

This issue is basically about that bold thingy from the comment.

**Comment by per-samuelsson** [comment]
Note to self: update http://starcounter.io/guides/tools/weaver/ to include guide on how to diagnose.

**Comment by per-samuelsson** [comment]
> Note to self: update http://starcounter.io/guides/tools/weaver/ to include guide on how to diagnose.

And when doing so, drop the section on bootstrap weaving since we have abandoned that.

**Comment by per-samuelsson** [comment]
> And when doing so, drop the section on bootstrap weaving since we have abandoned that.

Done.

**Comment by per-samuelsson** [comment]
Implemented, merged, pushed into **develop** (https://github.com/Starcounter/Starcounter/commit/ef1355f03e18caa855cc537ef69e8468fa70090d).

Remaining: finalizing the new documentation at [Troubleshooting weaver failures](http://starcounter.io/guides/tools/weaver/#troubleshooting-weaver-failures), and merging into **pnext**.

**Comment by per-samuelsson** [comment]
> Remaining: finalizing the new documentation at [Troubleshooting weaver failures](http://starcounter.io/guides/tools/weaver/#troubleshooting-weaver-failures)

Done also.

However, the sample output looks kind of shitty unfortunately, which is bit of a shame when I spent some energy to get it as readable as possible when extending the weaver and the new diagnostic provisioning. For some reason, WP seem to **both** add a horizontal scrollbar **and** still crop the content? And also do some highlighting that I can't really get a grip on.

Below is how I want it to look.

@warpech, do you have any pointers on how the formatting can be improved?

```
C:\Users\Per\Bogota\bin\Debug>scweaver --nocache --verbosity=diagnostic bogota.exe 

=== Bootstrap diagnostics ===
Code weaver:
  Input directory: C:\Users\Per\Bogota\bin\Debug
  Output directory: C:\Users\Per\Bogota\bin\Debug\.starcounter
  Application file: bogota.exe
  Disable edition libraries: False
  Disable cache: True
  Weave only to cache: False
Weaver cache:
  Cache directory: C:\Users\Per\Bogota\bin\Debug\.starcounter\cache
  Disabled: True
  4 search directories:
  C:\Users\Per\Bogota\bin\Debug
  C:\Users\Per\Git\Starcounter
  C:\Users\Per\Git\Starcounter\EditionLibraries
  C:\Users\Per\Git\Starcounter\LibrariesWithDatabaseClasses
File exclusion policy:
  5 weaver.ignore files:
  Newtonsoft.Json.dll
  CommandLine.dll
  ImageGlue.dll
  CsvHelper.dll
  unins000.exe
File manager:
  Source directory: C:\Users\Per\Bogota\bin\Debug
  Target directory: C:\Users\Per\Bogota\bin\Debug\.starcounter
  12 input files considered.
  C:\Users\Per\Bogota\bin\Debug:
    Concepts.Ring8.Bogota.dll:
    ImageGlue.dll:
    Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll:
    Newtonsoft.Json.dll:
    Bogota.Common.dll:
    bogota.exe:
  C:\Users\Per\Git\Starcounter\EditionLibraries:
    Simplified.Data.Model.dll:
    SocietyObjects.Concepts.Ring1.dll:
    SocietyObjects.Concepts.Ring2.dll:
    SocietyObjects.Concepts.Ring3.dll:
    SocietyObjects.Concepts.Ring4.dll:
  C:\Users\Per\Git\Starcounter\LibrariesWithDatabaseClasses:
    Starcounter.Extensions.dll:
======
Retieving files to weave.
Not reusing cached assembly "Concepts.Ring8.Bogota.dll": The cache was disabled.
Not processing assembly ImageGlue.dll: it's excluded by policy.
Not reusing cached assembly "Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll": The cache was disabled.
Not processing assembly Newtonsoft.Json.dll: it's excluded by policy.
Not reusing cached assembly "Bogota.Common.dll": The cache was disabled.
Not reusing cached assembly "bogota.exe": The cache was disabled.
Not reusing cached assembly "Simplified.Data.Model.dll": The cache was disabled.
Not reusing cached assembly "SocietyObjects.Concepts.Ring1.dll": The cache was disabled.
Not reusing cached assembly "SocietyObjects.Concepts.Ring2.dll": The cache was disabled.
Not reusing cached assembly "SocietyObjects.Concepts.Ring3.dll": The cache was disabled.
Not reusing cached assembly "SocietyObjects.Concepts.Ring4.dll": The cache was disabled.
Not reusing cached assembly "Starcounter.Extensions.dll": The cache was disabled.
Retreived 10 files to weave.
Weaving C:\Users\Per\Bogota\bin\Debug\Concepts.Ring8.Bogota.dll.
Detected reference: mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\assembly\GAC_64\mscorlib\2.0.0.0__b77a5c561934e089\mscorlib.dll: not part of inclusion set.
Weaving C:\Users\Per\Git\Starcounter\EditionLibraries\SocietyObjects.Concepts.Ring1.dll.
Not analyzing/weaving C:\Users\Per\Git\Starcounter\Starcounter.dll: not part of inclusion set.
Not analyzing/weaving C:\Users\Per\Git\Starcounter\Starcounter.Internal.dll: not part of inclusion set.
Weaving C:\Users\Per\Git\Starcounter\EditionLibraries\SocietyObjects.Concepts.Ring2.dll.
Detected reference: system, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll: not part of inclusion set.
Weaving C:\Users\Per\Git\Starcounter\EditionLibraries\SocietyObjects.Concepts.Ring4.dll.
Weaving C:\Users\Per\Git\Starcounter\EditionLibraries\SocietyObjects.Concepts.Ring3.dll.
Detected reference: newtonsoft.json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed.
Not analyzing/weaving C:\Users\Per\Bogota\bin\Debug\Newtonsoft.Json.dll: not part of inclusion set.
Detected reference: system.core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll: not part of inclusion set.
Detected reference: microsoft.csharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll: not part of inclusion set.
Weaving C:\Users\Per\Bogota\bin\Debug\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll.
Detected reference: system.data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\assembly\GAC_64\System.Data\2.0.0.0__b77a5c561934e089\System.Data.dll: not part of inclusion set.
Detected reference: system.web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
Not analyzing/weaving C:\WINDOWS\assembly\GAC_64\System.Web\2.0.0.0__b03f5f7f11d50a3a\System.Web.dll: not part of inclusion set.
Detected reference: system.configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
Not analyzing/weaving C:\WINDOWS\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll: not part of inclusion set.
Detected reference: system.web.services, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
Not analyzing/weaving C:\WINDOWS\assembly\GAC_MSIL\System.Web.Services\2.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll: not part of inclusion set.
Detected reference: microsoft.visualstudio.qualitytools.utfresources, Version=10.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
Not analyzing/weaving C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.QualityTools.UTFResources\10.1.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.QualityTools.UTFResources.dll: not part of inclusion set.
Weaving C:\Users\Per\Bogota\bin\Debug\Bogota.Common.dll.
Detected reference: starcounter.xson, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf.
Not analyzing/weaving C:\Users\Per\Git\Starcounter\Starcounter.XSON.dll: not part of inclusion set.
Detected reference: system.servicemodel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll: not part of inclusion set.
Detected reference: system.xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll: not part of inclusion set.
Detected reference: system.drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll: not part of inclusion set.
Detected reference: starcounter.logging, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf.
Not analyzing/weaving C:\Users\Per\Git\Starcounter\Starcounter.Logging.dll: not part of inclusion set.
Detected reference: system.runtime.serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll: not part of inclusion set.
Detected reference: imageglue, Version=7.4.0.0, Culture=neutral, PublicKeyToken=d78d2cea5dcfdc98.
Not analyzing/weaving C:\Users\Per\Bogota\bin\Debug\ImageGlue.dll: not part of inclusion set.
Detected reference: system.io.compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression\v4.0_4.0.0.0__b77a5c561934e089\System.IO.Compression.dll: not part of inclusion set.
Detected reference: system.io.compression.filesystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Not analyzing/weaving C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression.FileSystem\v4.0_4.0.0.0__b77a5c561934e089\System.IO.Compression.FileSystem.dll: not part of inclusion set.
Weaving C:\Users\Per\Bogota\bin\Debug\bogota.exe.
Weaving C:\Users\Per\Git\Starcounter\EditionLibraries\Simplified.Data.Model.dll.
Weaving C:\Users\Per\Git\Starcounter\LibrariesWithDatabaseClasses\Starcounter.Extensions.dll.
=== Finalization diagnostics ===
Code weaver:
  19 assemblies actually referenced:
  mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  system, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  newtonsoft.json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
  system.core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  microsoft.csharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  system.data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  system.web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  system.configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  system.web.services, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  microsoft.visualstudio.qualitytools.utfresources, Version=10.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  starcounter.xson, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf
  system.servicemodel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  system.xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  system.drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  starcounter.logging, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf
  system.runtime.serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  imageglue, Version=7.4.0.0, Culture=neutral, PublicKeyToken=d78d2cea5dcfdc98
  system.io.compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  system.io.compression.filesystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  31 assemblies in weaver domain:
  C:\Users\Per\Bogota\bin\Debug:
    Concepts.Ring8.Bogota.dll:
    Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll:
    Bogota.Common.dll:
    bogota.exe:
    Newtonsoft.Json.dll:
    ImageGlue.dll:
  C:\Users\Per\Git\Starcounter\EditionLibraries:
    Simplified.Data.Model.dll:
    SocietyObjects.Concepts.Ring1.dll:
    SocietyObjects.Concepts.Ring2.dll:
    SocietyObjects.Concepts.Ring3.dll:
    SocietyObjects.Concepts.Ring4.dll:
  C:\Users\Per\Git\Starcounter\LibrariesWithDatabaseClasses:
    Starcounter.Extensions.dll:
  C:\WINDOWS\assembly\GAC_64\mscorlib\2.0.0.0__b77a5c561934e089:
    mscorlib.dll:
  C:\Users\Per\Git\Starcounter:
    Starcounter.dll:
    Starcounter.Internal.dll:
    Starcounter.XSON.dll:
    Starcounter.Logging.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089:
    System.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089:
    System.Core.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a:
    Microsoft.CSharp.dll:
  C:\WINDOWS\assembly\GAC_64\System.Data\2.0.0.0__b77a5c561934e089:
    System.Data.dll:
  C:\WINDOWS\assembly\GAC_64\System.Web\2.0.0.0__b03f5f7f11d50a3a:
    System.Web.dll:
  C:\WINDOWS\assembly\GAC_MSIL\System.Configuration\2.0.0.0__b03f5f7f11d50a3a:
    System.Configuration.dll:
  C:\WINDOWS\assembly\GAC_MSIL\System.Web.Services\2.0.0.0__b03f5f7f11d50a3a:
    System.Web.Services.dll:
  C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.QualityTools.UTFResources\10.1.0.0__b03f5f7f11d50a3a:
    Microsoft.VisualStudio.QualityTools.UTFResources.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089:
    System.ServiceModel.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089:
    System.Xml.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a:
    System.Drawing.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089:
    System.Runtime.Serialization.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression\v4.0_4.0.0.0__b77a5c561934e089:
    System.IO.Compression.dll:
  C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.IO.Compression.FileSystem\v4.0_4.0.0.0__b77a5c561934e089:
    System.IO.Compression.FileSystem.dll:
======
```

**Comment by per-samuelsson** [comment]
Can't complete this, because of #3422 when I'm trying to merge it into **pnext**, so I'm doing something else in between.

**Comment by per-samuelsson** [comment]
> Can't complete this, because of #3422 when I'm trying to merge it into **pnext**, so I'm doing something else in between.

Seem we don't have the same kind of policies for pushing stuff to **pnext** and that it builds is not a requirement at this moment. There have been quite a few commits and merges after #3422 broke the build, and now latest **develop** was merged too, so this stuff came along in that.

Then this one is done.

**Comment by k-rus** [comment]
> Seem we don't have the same kind of policies for pushing stuff to pnext

We do have the policy (I guess it is still not written), but as I see many developers in the company ignores it. There are even developers who pushes changes into `develop` without running personal builds on personal branches.
