### ISSUE TITLE
Deleting a database very often gives no result

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Starcounter#3896]
It very often happens that clicking the `Delete` button and confirming the deletion of a database does nothing. No errors on console, no loading icon, just nothing.

Sometimes it happens that trying to delete a database shows dialog box that the database is running, while the `Start` button is active, and the database handlers do not respond.

Most of the time it happens when the database is in crash or inconsistent state.

This is very annoying, and should be fixed. Whatever is happening it should be properly displayed to the user. The database deletion should also be fixed, even inconsistent or crashed databases should be properly deleted.

**Comment by Mnosek** [comment]
I have faced the same problem couple times.

**Comment by dan31** [comment]
@andwah could you prioritise this one? I recall we have it for really long time, and it is actually pretty annoying. I believe the fix should go to both ```develop``` and ```pnext```. CC @per-samuelsson

**Comment by per-samuelsson** [comment]
> @andwah could you prioritise this one? I recall we have it for really long time, and it is actually pretty annoying. I believe the fix should go to both develop and pnext. CC @per-samuelsson

@andwah, let me know if you have any questions about the inner admin server bits and I can help you out.

**Comment by andwah** [comment]
> It very often happens that clicking the Delete button and confirming the deletion of a database does nothing. No errors on console, no loading icon, just nothing.

This can be that the session has timed out, Admin is using half angular half puppets, so maybe the admin is using the old puppets  without the "reconnect/ping" thing.

> Sometimes it happens that trying to delete a database shows dialog box that the database is running, while the Start button is active, and the database handlers do not respond.
> 
> Most of the time it happens when the database is in crash or inconsistent state.

I will check where this can go wrong.

**Comment by miyconst** [comment]
>This can be that the session has timed out, Admin is using half angular half puppets, so maybe the admin is using the old puppets without the "reconnect/ping" thing.

@andwah, this is not the case. I always check console and patches for errors. The connection was live. And the other buttons/actions work as they should.

**Comment by andwah** [comment]
@miyconst Thanks good , then i can keep check for other causes.

**Comment by andwah** [comment]
I fixed how the database running state was evaluated.

**Comment by andwah** [comment]
Can this be closed?

**Comment by miyconst** [comment]
Let's close it for now, if I met it ever again, I will reopen. Thanks for the fixing.

**Comment by miyconst** [comment]
Just got exactly the same behavior once again. The database was after a crash.

```
Starcounter-RC-2.3.0.5364 (Dec 13, 2016 3:02:21 AM)
```

**Comment by dan31** [comment]
@andwah we are still facing this in 2.3 and above. Please have a look and address.
